name: Unit Test
on:
  push:
    branches: [master]
jobs:
  j:
    name: Build and Run
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: VC Vars
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: "14.38.33130"
      - name: Check ASAN DLL
        run: where.exe clang_rt.asan_dynamic-x86_64.dll
      - name: Configure
        run: cmake .
      - name: Build and Run
        run: cmake --build . --config Debug --target run-repro
